/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#2f3131",
        "secondary-container": "#4a4949",
        "primary": "#48dada",
        "on-primary-fixed-variant": "#004f4f",
        "outline": "#859393",
        "outline-variant": "#3c4949",
        "on-secondary-container": "#bab8b7",
        "primary-fixed-dim": "#48dada",
        "inverse-surface": "#e3e2e2",
        "surface-dim": "#121414",
        "on-primary-fixed": "#002020",
        "secondary": "#c9c6c5",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-variant": "#343535",
        "on-tertiary-container": "#3d3f3f",
        "tertiary-fixed": "#e2e2e2",
        "tertiary": "#c6c6c7",
        "surface-container-highest": "#343535",
        "on-background": "#e3e2e2",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-low": "#1a1c1c",
        "surface-tint": "#48dada",
        "tertiary-container": "#a9aaaa",
        "primary-fixed": "#6bf7f7",
        "on-surface": "#e3e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "on-error": "#690005",
        "on-secondary": "#313030",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary": "#003737",
        "surface-container": "#1e2020",
        "surface-container-lowest": "#0d0e0f",
        "inverse-on-surface": "#2f3131",
        "surface": "#121414",
        "secondary-fixed": "#e5e2e1",
        "surface-container-high": "#292a2a",
        "primary-container": "#0fbdbd",
        "on-primary-container": "#004747",
        "surface-bright": "#383939",
        "on-surface-variant": "#bbc9c9",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006a6a",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-fixed": "#1c1b1b",
        "background": "#121414"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
